### ISSUE TITLE
Does not support creating new Adapters 

### ISSUE THREAD

**Issue by hanneslueke** [industrial-edge/iih-essentials-development-kit#29]
## Summary

For Some reason you do not allow to create new adapters and i cannot fathom why. I wanted to develop a new connecter for my application. therefor i require the ability to create new adapters in the IIH essentials devKit. 

This is not possible.

## Version of the used components

latest IIH Essentials DevKit

## Steps to reproduce

Creating a new Adapters on the UI or REST-API fails.

## What is the current bug behavior?

Adapter creation is denied: 
![image](https://github.com/industrial-edge/iih-essentials-development-kit/assets/152261405/c27f6fc4-5817-4c40-bd73-935807484795)

## What is the expected correct behavior?

Creation of an Adaper is possible

**Comment by KohlerL-Smns** [comment]
Thanks for reaching out. Unfortunately, adding multiple adapters is currently not supported in the development kit.
We will enable this in the next release 1.10.0 first half of February.

**Comment by hanneslueke** [comment]
That are awesome news. :D

**Comment by KohlerL-Smns** [comment]
The Dev Kit was updated to 1.10.0. Creating new connectors is now possible.
